name: Deploy Backend

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Frontend CD" ]
    types: [ completed ]

jobs:
  deploy-convex:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CLERK_PUBLISHABLE_KEY: ""
      CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: ""
      CLERK_SIGN_IN_URL: ""
      CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: ""
      CLERK_SIGN_UP_URL: ""
      CONVEX_URL: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup Doppler CLI
        uses: dopplerhq/cli-action@v4

      - name: Fetch secrets from Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_AT_TOKENS }}
        run: |
          doppler secrets download \
            --no-file \
            --format env \
            --project books \
            --config prd_tokens \
            | sed 's/"//g' >> $GITHUB_ENV

      - name: Setup Convex Prod
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_AT_SECRETS }}
        run: |
          echo "CLERK_PUBLISHABLE_KEY=${{ env.CLERK_PUBLISHABLE_KEY }}" > .env.local
          echo "CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=${{ env.CLERK_SIGN_IN_FALLBACK_REDIRECT_URL }}" >> .env.local
          echo "CLERK_SIGN_IN_URL=${{ env.CLERK_SIGN_IN_URL }}" >> .env.local
          echo "CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=${{ env.CLERK_SIGN_UP_FALLBACK_REDIRECT_URL }}" >> .env.local
          echo "CLERK_SIGN_UP_URL=${{ env.CLERK_SIGN_UP_URL }}" >> .env.local
          echo "CONVEX_URL=${{ env.CONVEX_URL }}" >> .env.local
          doppler secrets download --no-file --format env --config prd_secrets >> .env.local
          npx convex deploy --prod

